apiVersion: v1
kind: Secret
metadata:
  name: s3-proxy-secret
type: Opaque
data:
  s3-proxy-identity: {{ .Values.s3proxy.s3.identity }}
  s3-proxy-credential: {{ .Values.s3proxy.s3.credential }}
  jclouds-identity: {{ .Values.s3proxy.jclouds.identity }}
  jclouds-credential: {{ .Values.s3proxy.jclouds.credential }}