{{- if .Values.resources.createS3Credentials -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.s3proxy.service.name }}-credentials
type: Opaque
stringData:
    credentials: |
        {
            "accounts": {
                "{{ .Values.s3proxy.service.name }}:{{ .Values.s3proxy.service.port }}": {}
            }
        }
{{- end }}