{{- if .Values.resources.createS3Credentials -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.s3proxy.service.name }}-credentials
type: Opaque
stringData:
    credentials: |
        { "accounts": {
{{- if .Values.s3proxy.service.auth.enabled }}
                "{{ .Values.s3proxy.service.auth.id }}@{{ .Values.s3proxy.service.name }}": { "secret" : "{{ .Values.s3proxy.service.auth.credential }}" }
{{- else }}
                "{{ .Values.s3proxy.service.name }}:{{ .Values.s3proxy.service.port }}": {}
{{- end }}
            }
        }
{{- end }}