apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fdb-kubernetes-operator-manager-scc-role
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints 
  verbs: 
  - use