---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdb-kubernetes-operator-manager-scc-rolebinding
subjects:
  - kind: ServiceAccount
    name: fdb-kubernetes-operator-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fdb-kubernetes-operator-manager-scc-role